version: "3.8"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shopper_db
    volumes:
      - shopper_db_data:/var/lib/mysql

  api:
    depends_on:
      - db
    build:
      context: .
      target: production
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - app_node_modules:/app/node_modules

volumes:
  shopper_db_data:
  app_node_modules:
