export enum ErrorCodeEnum {
    INVALID_DATA = "INVALID_DATA",
    INVALID_TYPE = "INVALID_TYPE",
    DOUBLE_REPORT = "DOUBLE_REPORT",
    MEASURE_NOT_FOUND = "MEASURE_NOT_FOUND",
    MEASURES_NOT_FOUND = "MEASURES_NOT_FOUND",
    CONFIRMATION_DUPLICATE = "CONFIRMATION_DUPLICATE",
    SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND",
}


